# Generated file - do not commit this file.
{
  "name": "todo_module",
  "version": "0.0.1",
  "publish_to": "none",
  "environment": {
    "sdk": ">=2.19.4 <3.0.0",
    "flutter": ">=1.17.0"
  },
  "description": "A new Flutter package project.",
  "dependencies": {
    "flutter": {
      "sdk": "flutter"
    },
    "core": {
      "path": "C:\\\\Users\\\\Ismael\\\\Desktop\\\\workspace\\\\todoApp\\\\core"
    },
    "dependencies": {
      "path": "C:\\\\Users\\\\Ismael\\\\Desktop\\\\workspace\\\\todoApp\\\\dependencies"
    }
  },
  "dev_dependencies": {
    "flutter_test": {
      "sdk": "flutter"
    },
    "flutter_lints": "^2.0.0"
  },
  "dependency_overrides": {
    "core": {
      "path": "..\\\\core"
    },
    "dependencies": {
      "path": "..\\\\dependencies"
    }
  },
  "flutter": null
}